### ISSUE TITLE
The included Raspbian Lite image shows error message during boot

### ISSUE THREAD

**Issue by R4C3R** [raspberrypi/piserver#10]
When I use the Raspbian Lite image included with Pi Server, I see the following message during boot:

```
[FAILED] Failed to Start Create Volatile Files and Directories
See 'systemctl status systemd-tmpfiles-setup.service' for details
```

**Comment by maxnet** [comment]
Error itself is harmless.
But will get it fixed, since it indeed looks sloppy.
