### ISSUE TITLE
Cant load any pi client

### ISSUE THREAD

**Issue by m-gavrilyuk** [raspberrypi/piserver#101]
Help please 
![15858133159371630200497](https://user-images.githubusercontent.com/60624717/78222852-9af42d00-74ce-11ea-9812-e514b50c7043.jpg)

**Comment by m-gavrilyuk** [comment]
@maxnet 
I do averything like in manual and tftp coud not load any fail

**Comment by maxnet** [comment]
Judging by the screenshot you are running in standalone DHCP mode.
Only the Pi and the Piserver computer are connected to each other by an Ethernet switch that is connected to nothing else?

**Comment by m-gavrilyuk** [comment]
It work!! But I don't understand the difference between the switch and the cable directly.
