### ISSUE TITLE
Automatic add new pi

### ISSUE THREAD

**Issue by m-gavrilyuk** [raspberrypi/piserver#102]
Is it possible to auto detect and add as a client new raspberry in network.
For example in some VLAN all raspberry was add as a client without GUI adding.

**Comment by maxnet** [comment]
Only if it is okay that ALL Pi are going to run same OS with no exceptions.

Requires that you add stuff to `/etc/dnsmasq.conf` to tag all Pi to piserver group, among the lines of:

```
dhcp-mac=set:piserver,B8:27:EB:*:*:*
dhcp-mac=set:piserver,DC:A6:32:*:*:*
```

And symlink tftproot to the boot folder of the OS you want to use for all.

```
cd /var/lib/piserver
sudo mv tftproot tftproot.old
sudo ln -sf os/name-of-os/boot tftproot 
```

**Comment by m-gavrilyuk** [comment]
Thanks for quick answer. Maybe add some wiki for questions for dont open new issue every time ?) Thanks
