### ISSUE TITLE
Hangs on boot to GUI

### ISSUE THREAD

**Issue by OkenKhuman** [raspberrypi/piserver#112]
When I boot to console there is no problem but when I try booting into GUI desktop client RPi got hang.

I enabled the GUI boot by:
installing `lightdm`
enabling boot option to Desktop

But on booting it got stuck on rainbow splash screen.

What can I do to resolve this?

**Comment by maxnet** [comment]
I am guessing you are not using the "Raspberry Pi OS" that is provided by Piserver as base, as that already has lightdm by default. So what Linux distribution are you using instead? RPI OS Lite? Something else?

The modifications we normally do to make RPI OS suitable for read-only environments are listed here: https://github.com/raspberrypi/piserver/blob/master/scripts/convert_chrooted_cmds
May need to do those affecting lightdm manually. Like:

- add "tmpfs           /var/lib/lightdm  tmpfs defaults,mode=755,nosuid     0       0" to /etc/fstab manually.
- set user-authority-in-system-dir=true in /etc/lightdm/lightdm.conf

**Comment by OkenKhuman** [comment]
Thanks for the speedy reply.
I am using the "Raspbian Lite (version 2020-02-13)".

I will try out the the changes.

**Comment by OkenKhuman** [comment]
![20201022_165333.jpg](https://user-images.githubusercontent.com/34859716/96865222-4c68a900-1487-11eb-863a-76f00d9d78d9.jpg)

Seems like lightdm problem.

**Comment by maxnet** [comment]
Also make sure you have autologin disabled (unless you mounted /home/pi as tmpfs accordingly)

**Comment by OkenKhuman** [comment]
This GUI boot problem was solved with `Raspbian` image. No more GUI boot problem found. 
Thanks for help.
