### ISSUE TITLE
support for: loading to RAM and booting from it

### ISSUE THREAD

**Issue by OkenKhuman** [raspberrypi/piserver#120]
How can I prepare to make sure the image is loaded to RAM and booted from it.

My RPi4 is with 4GB and since booting from network does reduce the performance, I thought boot from RAM will help me a lot.

My target is to:
1) Mount root FS on RAM. (so that client will not change the actual image and fast in file system)
2) Mount /home (no change to piserver style).
3) Finally to make client have all privilege.

**Comment by OkenKhuman** [comment]
Sorry this is already there in the project.

I just have to modify some in image creation.

**Comment by m-gavrilyuk** [comment]
> Sorry this is already there in the project.
> 
> I just have to modify some in image creation.

Is this support only for PI4 ? 
when my pi 3 lost lan connection they just freeze and nothing work until connection will be restore

**Comment by OkenKhuman** [comment]
@m-gavrilyuk I think RPi3 is not a good option to be a client of the setup. 
But if you go for non graphic image it works fine for both Pi3 and Pi4.
