### ISSUE TITLE
Feature Request: Mass Shutdown/Reboot/Logout

### ISSUE THREAD

**Issue by locutusofsand** [raspberrypi/piserver#128]
I have a feature request to add Mass Shutdown/Reboot/Logout buttons to the PiServer interface to remotely effect all connected clients.  In my use case in an industrial setting where Pi's are distributed over a large square footage it can be a tedious task to reboot all of the devices to pull in changes/updates. 

Thank you.

**Comment by chengjianwen** [comment]
I have add the function like remote console, power off and reboot to piserver. But a console named kmscon are  required for clients.

I use them for a pi-classroom, and you can get it from: https://github.com/chengjianwen/piserver and https://github.com/chengjianwen/kmscon

Good luck for that.

**Comment by locutusofsand** [comment]
I did look into functionalities added and they were what i was looking for at the time but i ran into a new set of use cases that prompted me to look for another solution. 

In the end I just setup the managed switches to let me power cycle the POE to force a reboot.
