### ISSUE TITLE
Piserver and Bullseye

### ISSUE THREAD

**Issue by locutusofsand** [raspberrypi/piserver#139]
Will Piserver be offering the new Bullseye image? When I go to the Add page in Software it shows the newest version of Raspberry Pi OS as 2021-5-7 which I assume is the last Buster upgrade.

**Comment by maxnet** [comment]
Updating the convert script to fix a bug on Bullseye is on the todo list.

**Comment by locutusofsand** [comment]
I saw this update come through. Everything seems to be working for me. Thanks!
