### ISSUE TITLE
Mount shared directory to all clients

### ISSUE THREAD

**Issue by jonwitts** [raspberrypi/piserver#15]
It would be useful to be able to mount a directory from the PiServer to all clients that boot from it. I appreciate that this would be possible by altering the Raspbian image on the PiServer, but would a GUI to achieve this be useful for educators using the PiServer?

Thanks,
Jon

**Comment by maxnet** [comment]
Is the desire just to make a folder that the teacher prepared on piserver available on all clients read-only?

Or are you proposing shared folders multiple users should be able to write to?
If the latter, things like user groups and file system permissions would need more thought...

**Comment by jonwitts** [comment]
In the first instance the ability for the teacher to share resources to all users read-only would be ace. I could see the desire for read-write access too, but I would not imagine that that use case would be as common...
