### ISSUE TITLE
Installing OS from local file just unpacking the file

### ISSUE THREAD

**Issue by armin-kunkel** [raspberrypi/piserver#152]
Hi,
I have installed the PiServer (0.7.4 included in the newest Raspberry Pi OS Desktop Version) on a Laptop for testing purposes.

I was able to successfully boot an image downloaded from the internet (through the UI).

But first, I tried to install an image from a local file (`raspbian-lite.img.tar.xz`).
While booting a client and additionally capturing packets, I recognized that the file `bootcode.bin` was not found via TFTP.
In the `/var/lib/piserver/tftproot/` directory a symbolic link was created (MAC Address as link name).
But `file /var/lib/piserver/tftproot/MAC-ADDRESS` gave me the message `... broken symbolic link to /var/lib/piserver/os/raspbian-lite.img/boot`.
So I have been taken a look into `/var/lib/piserver/os/raspbian-lite.img/` and only saw one file called `2022-04-04-raspios-bullseye-armhf-lite.img`.

So it seems like, when installing an OS from a local file, the archive gets unpacked, but no further processing happens.

**Comment by maxnet** [comment]
"Local file" expects images that have already been converted for Piserver use, and that are in .tar.xz format. Which is not the same as standard disk images in .img.xz format.

You do can use the option "Import operating system from SD card" instead if you want to import existing SD cards.
