### ISSUE TITLE
piserver access password change

### ISSUE THREAD

**Issue by tlauritsen** [raspberrypi/piserver#153]
I have successfully set up a piserver for a bunch of Raspberry Pi's that are doing the slow control of a DAQ system using the EPICS control system.

Following the instructions, I installed the piserver from my own account. This unfortunately means that if I access the piserver (/usr/bin/piserver), I have to input my own personal password. For the final use, I would like to change this password to something else, to a password I can share with my group. I have not been able to figure out how to do that. I think the password is in '/var/lib/piserver/settings.json'. How can I change the piserver access password?

**Comment by maxnet** [comment]
Any user that is member of the "sudo" group should be able to start the Piserver GUI by entering the password of their own user account.
