### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by marc-odp** [raspberrypi/piserver#160]
Hi,
I have speakers in all my monitors but I get no audio. So I thought that it is because hdmi audio is not the default option in PiServer.
I started raspi-config in Piserver's Shell but when I want to see the sound options I get the message 'No internal audio devices found'.
How can I do the setup for the sound ?
Thanks.
marc
![image](https://github.com/raspberrypi/piserver/assets/17361839/f86284fe-ed93-4189-8d38-8414f9ea47b9)

**Comment by maxnet** [comment]
In case of Pi 4, it could also be that it wants to output audio of the wrong HDMI port.
Does it work any better if you try raspi-config's non-interactive mode?

`raspi-config nonint do_audio 0`
or
`raspi-config nonint do_audio 1`

**Comment by marc-odp** [comment]
Thank you.
I noticed that right clicking on the speaker icon on the right corner of the screen in the client brings a menu where it is possible to chose hdmi, so we are using that system for the moment and we get the sound. The option is memorized in the user profile it seems so no need to do it again and again.
I will try your solution when I get rid of my other problem (I create another topic).
