### ISSUE TITLE
Clients not booting any more

### ISSUE THREAD

**Issue by marc-odp** [raspberrypi/piserver#161]
Recently I added a lot of Pi since they became available again. We have now a lab with 48.
Today, it looks that most of the Pi were unable to boot. I have no clue why it happened.
My server is Mint 20 in a virtual machine and I have an external LDAP server in a docker container.
Boot is showing that some files are not found.
I went to see '/var/lib/piserver/tftproot/MAC_address/' and I don't see the folder 668dcc7e and the other files like pieeprom.sig
@maxnet : Could you put me on the right track to find the solution of this problem ? Thank you.

marc

![image](https://github.com/raspberrypi/piserver/assets/17361839/82107d37-1930-4355-8242-0823e6dd6fde)

**Comment by maxnet** [comment]
>I went to see '/var/lib/piserver/tftproot/MAC_address/' and I don't see the folder 668dcc7e and the other files like 
>pieeprom.sig

Does `ls -l --color /var/lib/piserver/tftproot` show the entire tftproot folder is empty?
Or are there broken symlinks shown in red?

Normally the folder has symbolic links like 668dcc7e -> /var/lib/piserver/os/your-os-image/boot
If something is wrong with "your-os-image", e.g. you deleted or decided to rename the folder manually, that could also result in dead links...
Can have the links recreated by assigning the Pi to an operating system image again in the Piserver GUI.

**Comment by maxnet** [comment]
Ignore my last message.

Can ignore the files not found.
It tries to look for files in the serial number subfolder first, which we do not use. But will go for the files in the root folder ( /var/lib/piserver/tftproot/mac_address ) next.
It does NOT need .sig or recovery files either.


Are it only the new Pi that are refusing to boot, or also existing ones?
You do are booting a recent OS image?
As I am not sure whether or not new Pi with new EEPROM firmware, are able to boot older start4.elf.

**Comment by marc-odp** [comment]
Thank you for responding so fast.
I am booting PiOS Full 32bits 2023-05-03. (So last version)
Both new ones and old ones are not booting. I have been told that 2 or 3 were working in the morning but later when I tried they were not booting.

**Comment by marc-odp** [comment]
192.168.1.167 is Piserver acting as proxy DHCP server.
192.168.1.1 is the router & DHCP server

**Comment by maxnet** [comment]
- Is the screenshot the actual point it hangs, and discontinues booting?
Or did it go a bit further, and was the screenshot only to demonstrate the "file not found" message?

- May want to double check with arping or similar tools that 192.168.1.167 is only being used by the Piserver server.

**Comment by marc-odp** [comment]
It hangs at that point.
I will check the other point tomorrow.
Thank you.

**Comment by marc-odp** [comment]
I was unable to precisely determine the source of the problem but at present, the Pi clients are booting nicely. Most certainly it was a network problem. I noticed that there was no static mapping for 192.168.1.167 in the router and fixed that.
I close the issue for now. Thank you !

**Comment by marc-odp** [comment]
Well... This will be probably the final word on the topic :
It was not a network problem.
The problem was that the Piserver host had no more free space...
After enlarging the VM virtual disk, the problem went away. :-)

**Comment by maxnet** [comment]
>The problem was that the Piserver host had no more free space...

Ah, yeah.
That is something that could use some improvement.
Currently no warnings on low disk space, nor are any quotas enforced, so a single student can make it run out.
