### ISSUE TITLE
Pi with MAC d8:3a:dd

### ISSUE THREAD

**Issue by jonwitts** [raspberrypi/piserver#163]
We are running PiServer on the buster release of Raspberry Pi Desktop...

I have just received some new PI 4s with the d8:3a:dd MAC addresses; any chance of getting commit 67a1513d8e6b6ec60458a6cfa81e97d046934bca backed into the Buster release too?

I know I really should upgrade my server to the latest release but mid-academic year is not my preferred point to make such changes! 

Jon

**Comment by maxnet** [comment]
If you need something fast, try:

```
sudo apt update
sudo apt install build-essential devscripts debhelper cmake libldap2-dev libgtkmm-3.0-dev libarchive-dev libcurl4-openssl-dev libcap-dev intltool git binfmt-support qemu-user-static
git clone --depth 1 https://github.com/raspberrypi/piserver.git
cd piserver
debuild -uc -us
cd ..
sudo apt install ./piserver*.deb
```

The source is not Pi OS version specific.

**Comment by jonwitts** [comment]
Thanks.

I bit the bullet and have installed a new PiServer VM with the Bullseye version of Raspberry Pi OS Desktop - should really get off Buster anyway!
