### ISSUE TITLE
Information Exposure Through Directory Listing (High 7 ~ 8.9)

### ISSUE THREAD

**Issue by Fla4sh** [raspberrypi/piserver#168]
Hello,
I dont know if this bug belong to this repo or another one but i have found 'Information Exposure Through Directory Listing' VIA https://archive.raspbian.org/

this link leaks '[raspbian.public.key](https://archive.raspbian.org/raspbian.public.key)
[snapshotindex.txt](https://archive.raspbian.org/snapshotindex.txt)'

and another files

**Comment by maxnet** [comment]
- Nothing to do with Piserver
- Public keys are meant to be public...
