### ISSUE TITLE
Add users / passwords from CSV file

### ISSUE THREAD

**Issue by ghollingworth** [raspberrypi/piserver#2]
Teachers use excel for this kind of stuff, it would be useful if we could open and read passwords from an xls or csv file

Need to think about what happens if you've got a repeated user (or a user that already exists)

Also if you've got a different password to the one that already exists...

**Comment by jonwitts** [comment]
Any idea when this change will be available through apt-get?

I have been working on a script of my own to do this, but it would be great to test this out for you in a school environment. https://www.raspberrypi.org/forums/viewtopic.php?f=116&t=199472&p=1254225#p1254209

Thanks,
Jon

**Comment by ghollingworth** [comment]
If you follow the build instructions on the front page (basically just running debuild) then you can dpkg -i the package to test yourself...

We'd likely package up any changes / improvements after another month or so...

**Comment by jonwitts** [comment]
Thanks Gordon. I have complied and install the latest version and will give it a test.

I ran into a few issues with package dependencies for libgtkmm-3.0-dev but that was resolved by installing aptitude and accepting a solution to downgrade it's dependent packages. 

Jon

**Comment by mitchellurgero** [comment]
I think the ability to use an external ldap (Windows Active Directory) server is a better option, this could be cool too though.

Lastest master code (as of my post) supports this.
