### ISSUE TITLE
Using tcp instead of udp

### ISSUE THREAD

**Issue by rprr** [raspberrypi/piserver#20]
How would one configure the nfs in piserver to use tcp instead of udp? This is in the case where the network can become a little unreliable. Thanks.

**Comment by maxnet** [comment]
Would require you to patch the piserver code, as any changes you make manual to cmdline.txt will be overwritten every time the IP of the piserver computer changes.

Change https://github.com/raspberrypi/piserver/blob/master/src/piserver.cpp#L505
To something like:

```
string newOptions = " ip=dhcp root=/dev/nfs nfsroot="+currentIP()+":"+kv.second->distroPath()+",v3,tcp";
```

(untested)

**Comment by rprr** [comment]
Many thanks for your prompt response. I did make the command line change (not source code) and was able to do nfs via tcp. However, the machine still freezes, if the network goes down. First I enabled sudo for the user on the client 'pi'. Then I tried to simulate a network unplug on the client 'pi' with the command: 

`sudo ip link set eth0 down
`

This freezes the client pi and a hard power unplug/replug is required. 

So, how can I make this client 'pi' more resilient under network outage conditions. 

Many thanks.

**Comment by rprr** [comment]
Many thanks for your explanation. 

However, I seem to recall that using the earlier method of using one pi as server and netbooting the second 'pi' with it did not suffer from this problem. 

[https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md](url)

If the network cable was unplugged, the client pi froze. However, if it was reconnected the client  would come back up after a few moments. I did this a while ago so maybe my recollection is not as good. I will try it again and report what happens when you use the method given above.

**Comment by maxnet** [comment]
Unplugging and replugging network cable is different from doing `sudo ip link set eth0 down`
With the command the link stays administratively down, no matter if you replug.

**Comment by rprr** [comment]
Unplug and replug with piserver also freezes the client pi. A power unplug/required reboot is required.

**Comment by maxnet** [comment]
Can you try if it works better if you go to the Piserver chroot shell of the OS, and disable dhcpcd there?

```
systemctl disable dhcpcd
```

That is the dhcp client that normally obtains a new lease if link goes down and up again. But that may be a problem in this case, because the program and scripts it calls are on nfs.

If you disable it, it will simply keep using the IP the kernel got from DHCP on boot.
(That does have the downside that it will not respect any expiry date, but will just keep using the IP indefinitely without DHCP server's blessing).
