### ISSUE TITLE
Custom /root and /boot

### ISSUE THREAD

**Issue by rprr** [raspberrypi/piserver#21]
I want to create a custom install based off the Raspbian Lite along with some additional programs, applications, as well as making some read/write directories. After making changes using the chroot, can I make a custom /root and /boot and install via .tar.xz using piserver? Then I could use these to install on various clients. Can I just go to chroot and do?

```
cd /
tar -cvpfJ /tmp/root.tar.xz --exclude='./boot'  --exclude='/tmp' .
tar -cvpfJ /tmp/boot.tar.xz boot
```

Thanks.

**Comment by maxnet** [comment]
Just one single tarball.

On main system:

```
cd /var/lib/piserver/os/Raspbian_Lite
sudo tar cJf /tmp/my_image.tar.xz *
```

**Comment by rprr** [comment]
Ooh, nice. :) Can we get a wiki for this git with these tricks?
