### ISSUE TITLE
Pis refuse to boot

### ISSUE THREAD

**Issue by rprr** [raspberrypi/piserver#23]
I'm able to set up the Pis but they refuse to boot. I looked at the logs on the server /var/log/syslog and they seem to get stuck right after the line which has something like vendor encap. The server definitely sees the pis but tftpboot fails. Can I turn on more debugging?

**Comment by maxnet** [comment]
Since you opened other issues before, I am assuming you did had success before.
Was that with same Pis/network?

**Comment by rprr** [comment]
It was working before. I moved it to a different location which required
some network changes. I must have messed something up. I have attempted to
go back from scratch many times but just can’t get it to work. I will
report back to see if I can fix it.

Thanks for your reply.

**Comment by rprr** [comment]
A little more progress. I'm able to boot, but only occasionally. Most of the time, the server does see the remote pi  and recognizes it by Mac address but somehow dnsmasq-tftp does not start to send over the bootcode.bin and other files.

**Comment by rprr** [comment]
It appears this may be connected to an arp filtering issue. Putting an sd card with just bootcode.bin netboots ok.

**Comment by rprr** [comment]
Just to follow up. I tried to test this issue with piserver directly on an x86 computer that had Raspbian Desktop freshly installed (no VM). The issue of the pis not being able to netboot consistently without the SD card persisted. It always seems to reliably boot as long as there is a FAT32 formatted micro SD card with bootcode.bin. I have not been able to determine the actual reason why the netboot without the SD card is unsuccessful.

**Comment by maxnet** [comment]
Probably Ethernet switch specific.

**Comment by rprr** [comment]
@maxnet -- Thanks. Closing this.
