### ISSUE TITLE
Assign static IP

### ISSUE THREAD

**Issue by rprr** [raspberrypi/piserver#24]
I have setup piserver to be a standalone dhcp server. How can I set the IPs it assigns to be static based on Mac address?

Thanks.

**Comment by maxnet** [comment]
Currently not supported in the GUI.
Not sure if there is much demand for that.

**Comment by rprr** [comment]
Thanks. But how can I set it via editing files. Your help is appreciated.

**Comment by maxnet** [comment]
Well, in `/etc/dnsmasq.d/piserver` you have lines like:

``
dhcp-host=11:22:33:44:55:66,set:piserver
``

And that would need to become:

``
dhcp-host=11:22:33:44:55:66,set:piserver,1.2.3.4,hostnameyouwant
``

There is a slight problem editing that file though.
Your changes will be overwritten by piserver eventually...

**Comment by rprr** [comment]
Thank you. Would there be a way to prevent that?

**Comment by rprr** [comment]
Thanks. Maybe I will try the first method.
I suppose the alternative is to have an external DHCP server.

**Comment by rprr** [comment]
I was able to get an external router to work serving static IPs.
