### ISSUE TITLE
ssh into the clients without password

### ISSUE THREAD

**Issue by rprr** [raspberrypi/piserver#25]
Is there any reason why password-less ssh using public key does not work on the net-booting pis? It offers the public key, but that does not seem to allow login. There are no errors reported. I did edit the sshd config files in the chroot to allow for PubKey Authentication.

**Comment by ZanderBrown** [comment]
Perhaps the fingerprint is wrong? Would have thought that would throw an error.

What exactly happens with "does not seem to allow login"

**Comment by rprr** [comment]
I have to provide the password.  Last few lines from the output of ssh -v -v -v

`debug1: Authentications that can continue: publickey,password
debug3: start over, passed a different list publickey,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/pi/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password
debug1: Trying private key: /home/pi/.ssh/id_dsa
debug3: no such identity: /home/pi/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /home/pi/.ssh/id_ecdsa
debug3: no such identity: /home/pi/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /home/pi/.ssh/id_ed25519
debug3: no such identity: /home/pi/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password`

**Comment by ZanderBrown** [comment]
Looks like it's wanting a DSA key instead of RSA, yours is likely to be RSA

**Comment by rprr** [comment]
I will try setting it up for dsa. Interestingly, I can login without password on the machine running piserver.

**Comment by maxnet** [comment]
What kind of user are you logging in as?
Logging in as root should be possible. Provided you put public key in `/root/.ssh/authorized_keys` inside the image, as well as created host keys (`ssh-keygen -A` in the chroot)

Logging in as user created inside piserver is not going to work.
Client needs to provide user password to piserver before it can mount home folder.
So without password, home folder is not mounted, and sshd cannot look inside home folder for ~/.ssh folder.

**Comment by rprr** [comment]
How do I create a root user for the client? Inside the chroot?

**Comment by maxnet** [comment]
There's already a local root user by default.
Just put public key in /root/.ssh/authorized_keys inside chroot

Do note that the root user will not have any writable storage by default, though.
So while you can login, and do things like read log files, there isn't much practical use beyond that.

**Comment by rprr** [comment]
maxnet -- Thank you so much for your help.

While I don't need a root user per se, these are my needs for the client pi's based on the following design.  

1. At boot, mount remote directories served from outside (not piserver) as read/write via NFS that will contain applications and logs
2. At boot, start up some applications in the NFS mounted directories above via init scripts that will set DIOs, read ADCs, set DACs connected via custom built HATs to control/monitor instruments.
3. At boot, start an RPC server that will accept requests to set and read above  DIOs, DACs, ADCs etc.
4. Read and write logs and other data to files on the the NFS mounted directories

As for the filesystem on the client, no need to do any read/write. I will have about ~8-10 client pi's connected to each piserver. Each of the clients will be mounting different NFS directories, as they will be running custom applications to control and monitor instrumentation. In addition, I will have 10 sets of these. So a total of almost 80-100 pi's :)

From a maintenance standpoint, having them netboot reliability is important.

I'm also looking at your other github repos such as gpioexpander and scriptexecutor. They sound very interesting.

**Comment by maxnet** [comment]
Ok, you should be able to get that working fine with just a custom `/etc/fstab` to mount your additional storage, and a `/etc/rc.local` startup script.


Regarding the boot reliably problem in your other issue. 
If it does work with a sd card with bootcode.bin chances are that it also does work on the newer 3+ model without SD card, as that one has newer bootcode that solves some earlier issues.
(For me it also works reliably with the older model though. So that's why I think whether or not you are affected by those bugs depends on network).

**Comment by rprr** [comment]
I have a 3bplus and I tried it but it gets stuck after the line sent bootcode.bin.

**Comment by maxnet** [comment]
>I have a 3bplus and I tried it but it gets stuck after the line sent bootcode.bin.

Are you using a Raspbian image that comes from the repository?
If so, you have a different problem, in that the files still have not been updated to latest version, and do not support the 3+.


For now, you will need to convert a stock Raspbian (Lite) image manually, convert it to piserver format, and add it to the system.

```
wget http://downloads.raspberrypi.org/raspbian_lite/boot.tar.xz
wget http://downloads.raspberrypi.org/raspbian_lite/root.tar.xz
/var/lib/piserver/scripts/convert.sh boot.tar.xz root.tar.xz Raspbian_Lite_for_piserver.tar.xz
```

**Comment by rprr** [comment]
Thanks. That did work. A cold start or power unplug/replug starts up the pi just fine. One issue I found is that, on reboot it does not come back up. I searched and there is an issue reported on the github raspberrypi firmware repo. 
[https://github.com/raspberrypi/firmware/issues/963]
Hopefully, there is a firmware fix for this.

**Comment by jmccoy555** [comment]
Works for me too with the new image (without sd card, haven't tested with), but also gets stuck on reboot.

**Comment by Anonymousdog** [comment]
I can show you how to setup sudo capabilities on these LTSP fat clients RPis.  SSH can be configured to look at different directories than ~; so, public key login might be possible too (although LDAP users would probably generate errors when ~ directory writes looks place (e.g., nano history).
