### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by emkookmer** [raspberrypi/piserver#33]
Is it possible to run PiServer in a Docker image instance?

**Comment by emkookmer** [comment]
Hi @maxnet,

I already understond that PiServer will run within a VirtualBox (or any other VM instance for that matter), but my Synology NAS doesn't support creating a real VM instance, but it has Docker support.

**Comment by dragon788** [comment]
It _is_ possible to run GUI applications from within Docker, you can use xpra or VNC within the container or you can share the X server socket from the host into the container. You are correct that it probably wouldn't work correctly on a Synology unless there was another container providing an Xserver.

I actually landed here with the same question, and I'll be looking into a way to do get it running in Docker if possible.

**Comment by HarvsG** [comment]
@dragon788 Did you ever have any luck? I would like to have it running in a Docker image on a box running OpenMediaVault.
