### ISSUE TITLE
Can't access via SSH after PXE boot

### ISSUE THREAD

**Issue by hypery11** [raspberrypi/piserver#34]
I have 16 Pis boot from x86 piserver,
after the booting process I want to ssh to the 16 Pis
but it shows up "connection reset by client"

![2018-08-25 9 08 53](https://user-images.githubusercontent.com/4160414/44618587-6f996d00-a8ab-11e8-8b50-456da8c4f21e.png)

PS. already `sudo raspi-config` to enable ssh

**Comment by maxnet** [comment]
From the chroot shell:

```
ssh-keygen -A
systemctl enable ssh
```

**Comment by hypery11** [comment]
THX, bro
