### ISSUE TITLE
Persistence for /home/pi

### ISSUE THREAD

**Issue by Summer88** [raspberrypi/piserver#36]
I've enabled autologin for  user pi, but I'm unable to change chromium preferences and customize toolbar.

Where are coming from the home folder files that are loaded as tmpfs from fstab line: 
`tmpfs           /home/pi           tmpfs   defaults            0       0`

If I edit files stored in server `/var/lib/piserver/os/Raspbian-2018-07-05/home/pi/Desktop/chromium-browser.desktop ` there's no effect at client reboot.

Is fstab on the client related to ` /var/lib/piserver/scripts/convert_chrooted_cmds`?

Could you please say me which file need to be edited to make temporarly writable the client desktop?
Thanks, BR

**Comment by maxnet** [comment]
>Where are coming from the home folder files that are loaded as tmpfs from fstab line:
>tmpfs /home/pi tmpfs defaults 0 0

If you added that line (it is not there by default), /home/pi will live in tmpfs (=ramdisk) and will be empty on each boot.

Can create your own startup script in `/etc/rc.local` to copy files from a different folder to /home/pi on each boot.
