### ISSUE TITLE
theoretical maxima clients

### ISSUE THREAD

**Issue by hypery11** [raspberrypi/piserver#46]
I was wonder is there any limit to max clients that pi-server supported?

may be cause by NFS mount limit or max number of socket on Debian?

and how to increase the limited clients?

**Comment by maxnet** [comment]
Theoretically: I recall that under Linux maximum number of sockets equals maximum number of file descriptors, and the maximum default for that is computed by the amount of memory your computer has.
Can simply override defaults by changing with sysctl settings though.

In practice: to have acceptable speed and not get packet loss, that would depend on how many 10 gigabit Ethernet cards you can fit in your server...
