### ISSUE TITLE
Raspbian "Lite", "Regular", "Full" ?

### ISSUE THREAD

**Issue by marc-odp** [raspberrypi/piserver#48]
I see that a new "Rapbian" version is available : "Raspbian Full".
How is it comparing with the regular "Raspbian" and "Raspbian Lite" ?
Thanks and Best Wishes for 2019 !
-marc-

**Comment by maxnet** [comment]
See: https://www.raspberrypi.org/blog/raspbian-update-november-2018/

What used to be called just "Raspbian" is now "Raspbian full"
Contains more software installed by default (Libreoffice, Scratch, Mathematica, Java) than the version without "full"
