### ISSUE TITLE
CM3 Support?

### ISSUE THREAD

**Issue by TheFlyingCrocodile** [raspberrypi/piserver#49]
just wondering if the compute module 3s will be detected and able to boot (even if i would have to use the same usb/eth controller as on the regular boards with the CM)

**Comment by maxnet** [comment]
Booting:

- Should be able to boot provided you have enabled network boot in OTP.
- May need to bring your own dt-blob.bin and other device tree files describing your hardware, and toss them in /var/lib/piserver/os/[name of os]/boot though

Detection:

- Should work by default, unless you program your own custom MAC addresses to the compute modules.
In that case change the OUI here: https://github.com/raspberrypi/piserver/blob/master/src/config.h#L22 and recompile.
