### ISSUE TITLE
wlan

### ISSUE THREAD

**Issue by chengjianwen** [raspberrypi/piserver#57]

**Comment by chengjianwen** [comment]
I setup a piserver for my daughter for test,  and noticed she never shutdown her pi every day. So I think maybe piserver should support WOL and reconnect to piserver when the pi server shutdown.

**Comment by maxnet** [comment]
I am afraid that is not a scenario that is possible to support.
Software components used expect 100% server availability. E.g. sshfs only authenticates the user to the server on login, and does not store password.
