### ISSUE TITLE
support for DietPi

### ISSUE THREAD

**Issue by hypery11** [raspberrypi/piserver#62]
I was try to use DietPi OS on piserver
but the custom os option only support .tar.xz file
the DietPi OS offer a .img file
is there anyway to using .img file for piserver?

**Comment by maxnet** [comment]
For what purpose do you want to use it?
Note that piserver is only suitable for multi-user desktop operating systems.

See for generic instructions on converting a SD card: https://github.com/raspberrypi/piserver/issues/55
If your OS is not on SD card, but still laying around as .img file on your hard disk, you can also use kpartx to mount the partitions.
