### ISSUE TITLE
Docker on a diskless Pi3

### ISSUE THREAD

**Issue by Rubique** [raspberrypi/piserver#66]
Hello sir,
I would like to set a cluster with PiServer and using a Docker.
I install on the server and on the chroot using "curl -sSL https://get.docker.com | sh"
On the server I write "sudo usermod -aG docker pi", then "sudo docker swarm init".
But, when I must join the manager with the client, it says "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running". I went to /var/run/ and I've seen there weren't Docker's files. 
I write "sudo systemctl status docker.service", on the server it says that the service is active but on the client, that says inactive (dead).

![systemctl_status_docker service](https://user-images.githubusercontent.com/51821574/59513025-3bcf1880-8eba-11e9-801f-55af6b15353d.jpg)

So I tried in the chroot "sudo systemctl enable docker.service", it doesn't work.
But, in the chroot_image I put "sudo dockerd" and it says "Error starting daemon: Devices cgroup isn't mounted".

![dockerd](https://user-images.githubusercontent.com/51821574/59513024-3bcf1880-8eba-11e9-8c88-3172283f02bc.jpg)

 Then, I tried to solve that problem by adding "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" in /boot/cmdline.txt via chroot. It doesn't work either.

![boot_cmdline txt](https://user-images.githubusercontent.com/51821574/59513227-b39d4300-8eba-11e9-9d8b-16c772ae3af1.jpg)

Would you have any idea ? 
Thanks in advance.
Florian

**Comment by emkookmer** [comment]
@Rubique what has been your solution for this problem ❓
