### ISSUE TITLE
can i change /etc files from client root

### ISSUE THREAD

**Issue by GDatviashvili** [raspberrypi/piserver#80]
i want to add printer from client and it says read only system

**Comment by maxnet** [comment]
Clients are not able to change files on the root file system, as the root file system is shared with multiple clients.


Suggest you install CUPS on the piserver server instead, and add the printer there.
Afterwards go to the piserver GUI, tab "software", select your Raspbian edition, press the shell button:

```
echo "export CUPS_SERVER=piserver" > /etc/profile.d/use-piserver-cups.sh
```
