### ISSUE TITLE
Journaling not supported on rootfs by Buster

### ISSUE THREAD

**Issue by gorky** [raspberrypi/piserver#83]
Attempting to set Journaling on the root filesystem in fstab results in the root filesystem being remounted 'ro' with errors.  Example fstab line:
PARTUUID=ff150ebc-02  /               ext4    defaults,data=journal  0       1

uname -a
Linux raspberrypi 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

Since ''/" is mounted ro, no logs (including syslog) are available (sorry).

**Comment by maxnet** [comment]
This repository is only about the piserver software.
A GUI for managing network booting Pi.
