### ISSUE TITLE
Different shared directory location

### ISSUE THREAD

**Issue by ramprao** [raspberrypi/piserver#87]
I want to use a completely different shared directory (`/rr`) that is exported from the piserver. Is this possible? So far not able to get it to work. 

In my /etc/exports on the piserver computer I have 
```
/var/lib/piserver/os *(ro,no_subtree_check,no_root_squash,fsid=1055)
/rr *(ro,no_subtree_check,no_root_squash,fsid=1055)
```
Then I do 
```
sudo exportfs -a
sudo /etc/init.d/nfs-kernel-server reload
```
In my /etc/fstab on the chroot, I have
```
piserver:/var/lib/piserver/os/shared   /mnt/shared      nfs     defaults,nolock,nofail,x-gvfs-show,x-gvfs-name=Shared%20folders    0       0
piserver:/rr   /s2      nfs     defaults,nolock,nofail    0       0
```
When the Pi boots, it mounts the /mnt/shared directory correctly. But the other directory at /s2 shows `piserver:/var/lib/piserver/os`.
```
piserver:/var/lib/piserver/os/shared                            20510464 10350080   9095424  54% /mnt/shared
piserver:/var/lib/piserver/os                                   20510464 10350080   9095424  54% /s2
```
I must be having my /etc/exports wrong, or is the piserver hardcoded to find shared directories under `/var/lib/piserver/os/`.

Thanks.

**Comment by maxnet** [comment]
>/var/lib/piserver/os *(ro,no_subtree_check,no_root_squash,fsid=1055)
>/rr *(ro,no_subtree_check,no_root_squash,fsid=1055)

Give /rr a different fsid number.

**Comment by ramprao** [comment]
Thank you.  :)
